export enum ModelNames {
    COUNTRIES = 'countries',
    CITIES = 'cities',
    CURRENCIES = 'currencies',
    UNIT_CATEGORIES = 'unit-categories',
    USERS = 'users',
    REFRESH_TOKENS = 'refresh-tokens',
    APP_SETTINGS = 'app-settings',
    SYSTEM_ADMINS = 'system-admins',
    UNITS = 'units',
    BOOKINGS = 'bookings',
    UNIT_REVIEWS = 'unit-reviews',
    UNIT_FAVOURITES = 'unit-favourites',
    OTP = 'otp',
}
