export enum API_TAGS {
    AUTH = 'Auth',
    USERS = 'Users',
    BOOKINGS = 'Bookings',
    COUNTRIES = 'Countries',
    CITIES = 'Cities',
    APP_SETTINGS = 'App Settings',
    CURRENCIES = 'Currencies',
    FORGET_PASSWORD = 'Forget Password',
    MAIL = 'Mail',
    OTP = 'OTP',
    UNITS = 'Units',
    UNIT_FAVORITES = 'Unit Favorites',
    UNIT_CATEGORIES = 'Unit Categories',
    SYSTEM_ADMINS = 'System Admins',
}
