export enum API_TAGS {
    AUTH = 'Auth',
    COUNTRIES = 'Countries',
    CITIES = 'Cities',
    APP_SETTINGS = 'App Settings',
    CURRENCIES = 'Currencies',
    UNIT_CATEGORIES = 'Unit Categories',
    SYSTEM_ADMINS = 'System Admins',
    BOOKINGS = 'Bookings',
    OTP = 'OTP',
    EMAIL_SERVICE = 'Email Service',
    FORGET_PASSWORD = 'Forget Password',
    UNIT_FAVOURITES = 'Unit Favourites',
    UNITS = 'Units',
}
